#! /usr/bin/env python3
from argparse import ArgumentParser
import subprocess

class Option: # Careful: there's an optparse class called 'Object'

    def __init__(self,_short,_long,_help,_dest):

        self.args    = [_short,_long]
        self.kwargs  = {'help' : _help, 'dest' : _dest}

    def __str__(self):
        return '\t' + '\t'.join(self.args) + '\t' + self.kwargs['help']

def main():

    # TODO create a "just-BibTex" option
    options = [
        Option("-a", "--aopt", "A option",'akey'),
        Option("-b", "--bopt", "B option",'bkey')
    ]

    # parse input
    parser = ArgumentParser()
    for option in options:
        parser.add_option(*option.args,**option.kwargs)
    for option in options:
        print(option)
    (cl_opts,cl_args) = parser.parse_args()
    print('opts',cl_opts)
    print('args',cl_args)
main()
